// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: customer/customer.proto

package customer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcCustomerService_GetCustomerById_FullMethodName = "/customer.GrpcCustomerService/GetCustomerById"
)

// GrpcCustomerServiceClient is the client API for GrpcCustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcCustomerServiceClient interface {
	GetCustomerById(ctx context.Context, in *GetCustomerRequestProto, opts ...grpc.CallOption) (*GetCustomerResponseProto, error)
}

type grpcCustomerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcCustomerServiceClient(cc grpc.ClientConnInterface) GrpcCustomerServiceClient {
	return &grpcCustomerServiceClient{cc}
}

func (c *grpcCustomerServiceClient) GetCustomerById(ctx context.Context, in *GetCustomerRequestProto, opts ...grpc.CallOption) (*GetCustomerResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerResponseProto)
	err := c.cc.Invoke(ctx, GrpcCustomerService_GetCustomerById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcCustomerServiceServer is the server API for GrpcCustomerService service.
// All implementations must embed UnimplementedGrpcCustomerServiceServer
// for forward compatibility.
type GrpcCustomerServiceServer interface {
	GetCustomerById(context.Context, *GetCustomerRequestProto) (*GetCustomerResponseProto, error)
	mustEmbedUnimplementedGrpcCustomerServiceServer()
}

// UnimplementedGrpcCustomerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcCustomerServiceServer struct{}

func (UnimplementedGrpcCustomerServiceServer) GetCustomerById(context.Context, *GetCustomerRequestProto) (*GetCustomerResponseProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerById not implemented")
}
func (UnimplementedGrpcCustomerServiceServer) mustEmbedUnimplementedGrpcCustomerServiceServer() {}
func (UnimplementedGrpcCustomerServiceServer) testEmbeddedByValue()                             {}

// UnsafeGrpcCustomerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcCustomerServiceServer will
// result in compilation errors.
type UnsafeGrpcCustomerServiceServer interface {
	mustEmbedUnimplementedGrpcCustomerServiceServer()
}

func RegisterGrpcCustomerServiceServer(s grpc.ServiceRegistrar, srv GrpcCustomerServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrpcCustomerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcCustomerService_ServiceDesc, srv)
}

func _GrpcCustomerService_GetCustomerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCustomerServiceServer).GetCustomerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcCustomerService_GetCustomerById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCustomerServiceServer).GetCustomerById(ctx, req.(*GetCustomerRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcCustomerService_ServiceDesc is the grpc.ServiceDesc for GrpcCustomerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcCustomerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.GrpcCustomerService",
	HandlerType: (*GrpcCustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomerById",
			Handler:    _GrpcCustomerService_GetCustomerById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer/customer.proto",
}
