services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --save 60 1 --loglevel warning --requirepass d4B$8fF@z1N#kPq!L9wT3vX%7gR5hY2sJ6mU+0aE4cI^

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540 
    restart: always
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: G5!kT@2y9B#zU8%w
      MYSQL_DATABASE: bookshop
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
