version: '3.8'

# redis-cli -h localhost -p 6380
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --save 60 1 --loglevel warning --requirepass d4B$8fF@z1N#kPq!L9wT3vX%7gR5hY2sJ6mU+0aE4cI^

    networks:
      - redis-example

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540 
    restart: always
    networks:
      - redis-example

# set network name redis-example
networks:
  redis-example:
    name: redis-example