version: '3.9'

services:
 user_svc_backend:
  
  container_name: user_svc_backend
  
  build:
    context: .
    dockerfile: Dockerfile.dev
  
  volumes:
    - ./UserService:/src/UserService   # Mount only the service folder
    - ~/.nuget/packages:/root/.nuget/packages # Use host NuGet cache

  networks:
    - bookshop-network


  # Map local machine port to Container port
  ports:
    - "5045:5045"

networks:
  bookshop-network:
    external: true