// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: customer/address/customer-address.proto

package customer_address

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcCustomerAddressService_GetCustomerAddress_FullMethodName = "/customerAddress.GrpcCustomerAddressService/GetCustomerAddress"
)

// GrpcCustomerAddressServiceClient is the client API for GrpcCustomerAddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcCustomerAddressServiceClient interface {
	GetCustomerAddress(ctx context.Context, in *GetCustomerAddressRequestProto, opts ...grpc.CallOption) (*GetCustomerAddressResponseProto, error)
}

type grpcCustomerAddressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcCustomerAddressServiceClient(cc grpc.ClientConnInterface) GrpcCustomerAddressServiceClient {
	return &grpcCustomerAddressServiceClient{cc}
}

func (c *grpcCustomerAddressServiceClient) GetCustomerAddress(ctx context.Context, in *GetCustomerAddressRequestProto, opts ...grpc.CallOption) (*GetCustomerAddressResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerAddressResponseProto)
	err := c.cc.Invoke(ctx, GrpcCustomerAddressService_GetCustomerAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcCustomerAddressServiceServer is the server API for GrpcCustomerAddressService service.
// All implementations must embed UnimplementedGrpcCustomerAddressServiceServer
// for forward compatibility.
type GrpcCustomerAddressServiceServer interface {
	GetCustomerAddress(context.Context, *GetCustomerAddressRequestProto) (*GetCustomerAddressResponseProto, error)
	mustEmbedUnimplementedGrpcCustomerAddressServiceServer()
}

// UnimplementedGrpcCustomerAddressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcCustomerAddressServiceServer struct{}

func (UnimplementedGrpcCustomerAddressServiceServer) GetCustomerAddress(context.Context, *GetCustomerAddressRequestProto) (*GetCustomerAddressResponseProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerAddress not implemented")
}
func (UnimplementedGrpcCustomerAddressServiceServer) mustEmbedUnimplementedGrpcCustomerAddressServiceServer() {
}
func (UnimplementedGrpcCustomerAddressServiceServer) testEmbeddedByValue() {}

// UnsafeGrpcCustomerAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcCustomerAddressServiceServer will
// result in compilation errors.
type UnsafeGrpcCustomerAddressServiceServer interface {
	mustEmbedUnimplementedGrpcCustomerAddressServiceServer()
}

func RegisterGrpcCustomerAddressServiceServer(s grpc.ServiceRegistrar, srv GrpcCustomerAddressServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrpcCustomerAddressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcCustomerAddressService_ServiceDesc, srv)
}

func _GrpcCustomerAddressService_GetCustomerAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerAddressRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCustomerAddressServiceServer).GetCustomerAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcCustomerAddressService_GetCustomerAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCustomerAddressServiceServer).GetCustomerAddress(ctx, req.(*GetCustomerAddressRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcCustomerAddressService_ServiceDesc is the grpc.ServiceDesc for GrpcCustomerAddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcCustomerAddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customerAddress.GrpcCustomerAddressService",
	HandlerType: (*GrpcCustomerAddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomerAddress",
			Handler:    _GrpcCustomerAddressService_GetCustomerAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer/address/customer-address.proto",
}
