// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: cart/cart.proto

package cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcCartService_GetCartItemByCustomerProto_FullMethodName = "/cart.GrpcCartService/GetCartItemByCustomerProto"
)

// GrpcCartServiceClient is the client API for GrpcCartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcCartServiceClient interface {
	GetCartItemByCustomerProto(ctx context.Context, in *CartItemRequestProto, opts ...grpc.CallOption) (*CartItemResponseProto, error)
}

type grpcCartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcCartServiceClient(cc grpc.ClientConnInterface) GrpcCartServiceClient {
	return &grpcCartServiceClient{cc}
}

func (c *grpcCartServiceClient) GetCartItemByCustomerProto(ctx context.Context, in *CartItemRequestProto, opts ...grpc.CallOption) (*CartItemResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemResponseProto)
	err := c.cc.Invoke(ctx, GrpcCartService_GetCartItemByCustomerProto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcCartServiceServer is the server API for GrpcCartService service.
// All implementations must embed UnimplementedGrpcCartServiceServer
// for forward compatibility.
type GrpcCartServiceServer interface {
	GetCartItemByCustomerProto(context.Context, *CartItemRequestProto) (*CartItemResponseProto, error)
	mustEmbedUnimplementedGrpcCartServiceServer()
}

// UnimplementedGrpcCartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcCartServiceServer struct{}

func (UnimplementedGrpcCartServiceServer) GetCartItemByCustomerProto(context.Context, *CartItemRequestProto) (*CartItemResponseProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartItemByCustomerProto not implemented")
}
func (UnimplementedGrpcCartServiceServer) mustEmbedUnimplementedGrpcCartServiceServer() {}
func (UnimplementedGrpcCartServiceServer) testEmbeddedByValue()                         {}

// UnsafeGrpcCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcCartServiceServer will
// result in compilation errors.
type UnsafeGrpcCartServiceServer interface {
	mustEmbedUnimplementedGrpcCartServiceServer()
}

func RegisterGrpcCartServiceServer(s grpc.ServiceRegistrar, srv GrpcCartServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrpcCartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcCartService_ServiceDesc, srv)
}

func _GrpcCartService_GetCartItemByCustomerProto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItemRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCartServiceServer).GetCartItemByCustomerProto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcCartService_GetCartItemByCustomerProto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCartServiceServer).GetCartItemByCustomerProto(ctx, req.(*CartItemRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcCartService_ServiceDesc is the grpc.ServiceDesc for GrpcCartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcCartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.GrpcCartService",
	HandlerType: (*GrpcCartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCartItemByCustomerProto",
			Handler:    _GrpcCartService_GetCartItemByCustomerProto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart/cart.proto",
}
