// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: customer-address.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer {

  /// <summary>Holder for reflection information generated from customer-address.proto</summary>
  public static partial class CustomerAddressReflection {

    #region Descriptor
    /// <summary>File descriptor for customer-address.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CustomerAddressReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZjdXN0b21lci1hZGRyZXNzLnByb3RvEg9jdXN0b21lckFkZHJlc3MiOwoe",
            "R2V0Q3VzdG9tZXJBZGRyZXNzUmVxdWVzdFByb3RvEhkKEWN1c3RvbWVyQWRk",
            "cmVzc0lkGAEgASgJIq0CCh9HZXRDdXN0b21lckFkZHJlc3NSZXNwb25zZVBy",
            "b3RvEg8KB2FkZHJlc3MYASABKAkSEAoIbGF0aXR1ZGUYAiABKAESEQoJbG9u",
            "Z2l0dWRlGAMgASgBEhMKBnN0cmVldBgEIAEoCUgAiAEBEhgKC3N1YkRpc3Ry",
            "aWN0GAUgASgJSAGIAQESFQoIZGlzdHJpY3QYBiABKAlIAogBARIVCghwcm92",
            "aW5jZRgHIAEoCUgDiAEBEhQKB2NvdW50cnkYCCABKAlIBIgBARIUCgd6aXBj",
            "b2RlGAkgASgJSAWIAQFCCQoHX3N0cmVldEIOCgxfc3ViRGlzdHJpY3RCCwoJ",
            "X2Rpc3RyaWN0QgsKCV9wcm92aW5jZUIKCghfY291bnRyeUIKCghfemlwY29k",
            "ZTKVAQoaR3JwY0N1c3RvbWVyQWRkcmVzc1NlcnZpY2USdwoSR2V0Q3VzdG9t",
            "ZXJBZGRyZXNzEi8uY3VzdG9tZXJBZGRyZXNzLkdldEN1c3RvbWVyQWRkcmVz",
            "c1JlcXVlc3RQcm90bxowLmN1c3RvbWVyQWRkcmVzcy5HZXRDdXN0b21lckFk",
            "ZHJlc3NSZXNwb25zZVByb3RvQlhaEi4vY3VzdG9tZXJfYWRkcmVzc6oCQVVz",
            "ZXJTZXJ2aWNlLkFwcHMuQ3VzdG9tZXJBZGRyZXNzZXMuR3JwYy5HcnBjQ3Vz",
            "dG9tZXJBZGRyZXNzU2VydmVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto), global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto.Parser, new[]{ "CustomerAddressId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto), global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto.Parser, new[]{ "Address", "Latitude", "Longitude", "Street", "SubDistrict", "District", "Province", "Country", "Zipcode" }, new[]{ "Street", "SubDistrict", "District", "Province", "Country", "Zipcode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetCustomerAddressRequestProto : pb::IMessage<GetCustomerAddressRequestProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetCustomerAddressRequestProto> _parser = new pb::MessageParser<GetCustomerAddressRequestProto>(() => new GetCustomerAddressRequestProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetCustomerAddressRequestProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.CustomerAddressReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCustomerAddressRequestProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCustomerAddressRequestProto(GetCustomerAddressRequestProto other) : this() {
      customerAddressId_ = other.customerAddressId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCustomerAddressRequestProto Clone() {
      return new GetCustomerAddressRequestProto(this);
    }

    /// <summary>Field number for the "customerAddressId" field.</summary>
    public const int CustomerAddressIdFieldNumber = 1;
    private string customerAddressId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CustomerAddressId {
      get { return customerAddressId_; }
      set {
        customerAddressId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetCustomerAddressRequestProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetCustomerAddressRequestProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CustomerAddressId != other.CustomerAddressId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CustomerAddressId.Length != 0) hash ^= CustomerAddressId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CustomerAddressId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CustomerAddressId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CustomerAddressId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CustomerAddressId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CustomerAddressId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomerAddressId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetCustomerAddressRequestProto other) {
      if (other == null) {
        return;
      }
      if (other.CustomerAddressId.Length != 0) {
        CustomerAddressId = other.CustomerAddressId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CustomerAddressId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CustomerAddressId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetCustomerAddressResponseProto : pb::IMessage<GetCustomerAddressResponseProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetCustomerAddressResponseProto> _parser = new pb::MessageParser<GetCustomerAddressResponseProto>(() => new GetCustomerAddressResponseProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetCustomerAddressResponseProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.CustomerAddressReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCustomerAddressResponseProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCustomerAddressResponseProto(GetCustomerAddressResponseProto other) : this() {
      address_ = other.address_;
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      street_ = other.street_;
      subDistrict_ = other.subDistrict_;
      district_ = other.district_;
      province_ = other.province_;
      country_ = other.country_;
      zipcode_ = other.zipcode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCustomerAddressResponseProto Clone() {
      return new GetCustomerAddressResponseProto(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    private string address_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Address {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 2;
    private double latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 3;
    private double longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "street" field.</summary>
    public const int StreetFieldNumber = 4;
    private readonly static string StreetDefaultValue = "";

    private string street_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Street {
      get { return street_ ?? StreetDefaultValue; }
      set {
        street_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "street" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStreet {
      get { return street_ != null; }
    }
    /// <summary>Clears the value of the "street" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStreet() {
      street_ = null;
    }

    /// <summary>Field number for the "subDistrict" field.</summary>
    public const int SubDistrictFieldNumber = 5;
    private readonly static string SubDistrictDefaultValue = "";

    private string subDistrict_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubDistrict {
      get { return subDistrict_ ?? SubDistrictDefaultValue; }
      set {
        subDistrict_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "subDistrict" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSubDistrict {
      get { return subDistrict_ != null; }
    }
    /// <summary>Clears the value of the "subDistrict" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSubDistrict() {
      subDistrict_ = null;
    }

    /// <summary>Field number for the "district" field.</summary>
    public const int DistrictFieldNumber = 6;
    private readonly static string DistrictDefaultValue = "";

    private string district_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string District {
      get { return district_ ?? DistrictDefaultValue; }
      set {
        district_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "district" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDistrict {
      get { return district_ != null; }
    }
    /// <summary>Clears the value of the "district" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDistrict() {
      district_ = null;
    }

    /// <summary>Field number for the "province" field.</summary>
    public const int ProvinceFieldNumber = 7;
    private readonly static string ProvinceDefaultValue = "";

    private string province_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Province {
      get { return province_ ?? ProvinceDefaultValue; }
      set {
        province_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "province" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasProvince {
      get { return province_ != null; }
    }
    /// <summary>Clears the value of the "province" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearProvince() {
      province_ = null;
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 8;
    private readonly static string CountryDefaultValue = "";

    private string country_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return country_ ?? CountryDefaultValue; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "country" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCountry {
      get { return country_ != null; }
    }
    /// <summary>Clears the value of the "country" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCountry() {
      country_ = null;
    }

    /// <summary>Field number for the "zipcode" field.</summary>
    public const int ZipcodeFieldNumber = 9;
    private readonly static string ZipcodeDefaultValue = "";

    private string zipcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Zipcode {
      get { return zipcode_ ?? ZipcodeDefaultValue; }
      set {
        zipcode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "zipcode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasZipcode {
      get { return zipcode_ != null; }
    }
    /// <summary>Clears the value of the "zipcode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearZipcode() {
      zipcode_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetCustomerAddressResponseProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetCustomerAddressResponseProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Address != other.Address) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitude, other.Latitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitude, other.Longitude)) return false;
      if (Street != other.Street) return false;
      if (SubDistrict != other.SubDistrict) return false;
      if (District != other.District) return false;
      if (Province != other.Province) return false;
      if (Country != other.Country) return false;
      if (Zipcode != other.Zipcode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Address.Length != 0) hash ^= Address.GetHashCode();
      if (Latitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitude);
      if (Longitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitude);
      if (HasStreet) hash ^= Street.GetHashCode();
      if (HasSubDistrict) hash ^= SubDistrict.GetHashCode();
      if (HasDistrict) hash ^= District.GetHashCode();
      if (HasProvince) hash ^= Province.GetHashCode();
      if (HasCountry) hash ^= Country.GetHashCode();
      if (HasZipcode) hash ^= Zipcode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Address);
      }
      if (Latitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Longitude);
      }
      if (HasStreet) {
        output.WriteRawTag(34);
        output.WriteString(Street);
      }
      if (HasSubDistrict) {
        output.WriteRawTag(42);
        output.WriteString(SubDistrict);
      }
      if (HasDistrict) {
        output.WriteRawTag(50);
        output.WriteString(District);
      }
      if (HasProvince) {
        output.WriteRawTag(58);
        output.WriteString(Province);
      }
      if (HasCountry) {
        output.WriteRawTag(66);
        output.WriteString(Country);
      }
      if (HasZipcode) {
        output.WriteRawTag(74);
        output.WriteString(Zipcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Address);
      }
      if (Latitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Longitude);
      }
      if (HasStreet) {
        output.WriteRawTag(34);
        output.WriteString(Street);
      }
      if (HasSubDistrict) {
        output.WriteRawTag(42);
        output.WriteString(SubDistrict);
      }
      if (HasDistrict) {
        output.WriteRawTag(50);
        output.WriteString(District);
      }
      if (HasProvince) {
        output.WriteRawTag(58);
        output.WriteString(Province);
      }
      if (HasCountry) {
        output.WriteRawTag(66);
        output.WriteString(Country);
      }
      if (HasZipcode) {
        output.WriteRawTag(74);
        output.WriteString(Zipcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Address.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
      }
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (HasStreet) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Street);
      }
      if (HasSubDistrict) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubDistrict);
      }
      if (HasDistrict) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(District);
      }
      if (HasProvince) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Province);
      }
      if (HasCountry) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (HasZipcode) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Zipcode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetCustomerAddressResponseProto other) {
      if (other == null) {
        return;
      }
      if (other.Address.Length != 0) {
        Address = other.Address;
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.HasStreet) {
        Street = other.Street;
      }
      if (other.HasSubDistrict) {
        SubDistrict = other.SubDistrict;
      }
      if (other.HasDistrict) {
        District = other.District;
      }
      if (other.HasProvince) {
        Province = other.Province;
      }
      if (other.HasCountry) {
        Country = other.Country;
      }
      if (other.HasZipcode) {
        Zipcode = other.Zipcode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Address = input.ReadString();
            break;
          }
          case 17: {
            Latitude = input.ReadDouble();
            break;
          }
          case 25: {
            Longitude = input.ReadDouble();
            break;
          }
          case 34: {
            Street = input.ReadString();
            break;
          }
          case 42: {
            SubDistrict = input.ReadString();
            break;
          }
          case 50: {
            District = input.ReadString();
            break;
          }
          case 58: {
            Province = input.ReadString();
            break;
          }
          case 66: {
            Country = input.ReadString();
            break;
          }
          case 74: {
            Zipcode = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Address = input.ReadString();
            break;
          }
          case 17: {
            Latitude = input.ReadDouble();
            break;
          }
          case 25: {
            Longitude = input.ReadDouble();
            break;
          }
          case 34: {
            Street = input.ReadString();
            break;
          }
          case 42: {
            SubDistrict = input.ReadString();
            break;
          }
          case 50: {
            District = input.ReadString();
            break;
          }
          case 58: {
            Province = input.ReadString();
            break;
          }
          case 66: {
            Country = input.ReadString();
            break;
          }
          case 74: {
            Zipcode = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
