// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: customer-address.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer {
  public static partial class GrpcCustomerAddressService
  {
    static readonly string __ServiceName = "customerAddress.GrpcCustomerAddressService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto> __Marshaller_customerAddress_GetCustomerAddressRequestProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto> __Marshaller_customerAddress_GetCustomerAddressResponseProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto, global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto> __Method_GetCustomerAddress = new grpc::Method<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto, global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCustomerAddress",
        __Marshaller_customerAddress_GetCustomerAddressRequestProto,
        __Marshaller_customerAddress_GetCustomerAddressResponseProto);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.CustomerAddressReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GrpcCustomerAddressService</summary>
    [grpc::BindServiceMethod(typeof(GrpcCustomerAddressService), "BindService")]
    public abstract partial class GrpcCustomerAddressServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto> GetCustomerAddress(global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GrpcCustomerAddressService</summary>
    public partial class GrpcCustomerAddressServiceClient : grpc::ClientBase<GrpcCustomerAddressServiceClient>
    {
      /// <summary>Creates a new client for GrpcCustomerAddressService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GrpcCustomerAddressServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcCustomerAddressService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GrpcCustomerAddressServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GrpcCustomerAddressServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GrpcCustomerAddressServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto GetCustomerAddress(global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCustomerAddress(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto GetCustomerAddress(global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCustomerAddress, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto> GetCustomerAddressAsync(global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCustomerAddressAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto> GetCustomerAddressAsync(global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCustomerAddress, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override GrpcCustomerAddressServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcCustomerAddressServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(GrpcCustomerAddressServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCustomerAddress, serviceImpl.GetCustomerAddress).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GrpcCustomerAddressServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCustomerAddress, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressRequestProto, global::UserService.Apps.CustomerAddresses.Grpc.GrpcCustomerAddressServer.GetCustomerAddressResponseProto>(serviceImpl.GetCustomerAddress));
    }

  }
}
#endregion
