// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cart/cart.proto
// Protobuf Java Version: 4.29.1

package com.example.catalog_svc.app.grpc.cart;

public interface CartItemProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.CartItemProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Corresponds to "bookId"
   * </pre>
   *
   * <code>string bookId = 1;</code>
   * @return The bookId.
   */
  java.lang.String getBookId();
  /**
   * <pre>
   * Corresponds to "bookId"
   * </pre>
   *
   * <code>string bookId = 1;</code>
   * @return The bytes for bookId.
   */
  com.google.protobuf.ByteString
      getBookIdBytes();

  /**
   * <pre>
   * Corresponds to "quantity"
   * </pre>
   *
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <pre>
   * Corresponds to "copiesAvailable"
   * </pre>
   *
   * <code>int32 copiesAvailable = 3;</code>
   * @return The copiesAvailable.
   */
  int getCopiesAvailable();

  /**
   * <pre>
   * Corresponds to "genre"
   * </pre>
   *
   * <code>string genre = 4;</code>
   * @return The genre.
   */
  java.lang.String getGenre();
  /**
   * <pre>
   * Corresponds to "genre"
   * </pre>
   *
   * <code>string genre = 4;</code>
   * @return The bytes for genre.
   */
  com.google.protobuf.ByteString
      getGenreBytes();

  /**
   * <pre>
   * Corresponds to "isbn"
   * </pre>
   *
   * <code>string isbn = 5;</code>
   * @return The isbn.
   */
  java.lang.String getIsbn();
  /**
   * <pre>
   * Corresponds to "isbn"
   * </pre>
   *
   * <code>string isbn = 5;</code>
   * @return The bytes for isbn.
   */
  com.google.protobuf.ByteString
      getIsbnBytes();

  /**
   * <pre>
   * Corresponds to "price"
   * </pre>
   *
   * <code>double price = 6;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <pre>
   * Corresponds to "publicationYear"
   * </pre>
   *
   * <code>string publicationYear = 7;</code>
   * @return The publicationYear.
   */
  java.lang.String getPublicationYear();
  /**
   * <pre>
   * Corresponds to "publicationYear"
   * </pre>
   *
   * <code>string publicationYear = 7;</code>
   * @return The bytes for publicationYear.
   */
  com.google.protobuf.ByteString
      getPublicationYearBytes();

  /**
   * <pre>
   * Corresponds to "title"
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * Corresponds to "title"
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
