// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cart/cart.proto
// Protobuf Java Version: 4.29.1

package com.example.catalog_svc.app.grpc.cart;

public interface CartItemResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.CartItemResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of CartItem
   * </pre>
   *
   * <code>repeated .cart.CartItemProto items = 1;</code>
   */
  java.util.List<com.example.catalog_svc.app.grpc.cart.CartItemProto> 
      getItemsList();
  /**
   * <pre>
   * A list of CartItem
   * </pre>
   *
   * <code>repeated .cart.CartItemProto items = 1;</code>
   */
  com.example.catalog_svc.app.grpc.cart.CartItemProto getItems(int index);
  /**
   * <pre>
   * A list of CartItem
   * </pre>
   *
   * <code>repeated .cart.CartItemProto items = 1;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * A list of CartItem
   * </pre>
   *
   * <code>repeated .cart.CartItemProto items = 1;</code>
   */
  java.util.List<? extends com.example.catalog_svc.app.grpc.cart.CartItemProtoOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   * A list of CartItem
   * </pre>
   *
   * <code>repeated .cart.CartItemProto items = 1;</code>
   */
  com.example.catalog_svc.app.grpc.cart.CartItemProtoOrBuilder getItemsOrBuilder(
      int index);
}
