// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cart/cart.proto
// Protobuf Java Version: 4.29.1

package com.example.catalog_svc.app.grpc.cart;

/**
 * Protobuf type {@code cart.CartItemProto}
 */
public final class CartItemProto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:cart.CartItemProto)
    CartItemProtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      CartItemProto.class.getName());
  }
  // Use CartItemProto.newBuilder() to construct.
  private CartItemProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CartItemProto() {
    bookId_ = "";
    genre_ = "";
    isbn_ = "";
    publicationYear_ = "";
    title_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.catalog_svc.app.grpc.cart.CartProto.internal_static_cart_CartItemProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.catalog_svc.app.grpc.cart.CartProto.internal_static_cart_CartItemProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.catalog_svc.app.grpc.cart.CartItemProto.class, com.example.catalog_svc.app.grpc.cart.CartItemProto.Builder.class);
  }

  public static final int BOOKID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bookId_ = "";
  /**
   * <pre>
   * Corresponds to "bookId"
   * </pre>
   *
   * <code>string bookId = 1;</code>
   * @return The bookId.
   */
  @java.lang.Override
  public java.lang.String getBookId() {
    java.lang.Object ref = bookId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bookId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Corresponds to "bookId"
   * </pre>
   *
   * <code>string bookId = 1;</code>
   * @return The bytes for bookId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBookIdBytes() {
    java.lang.Object ref = bookId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bookId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 2;
  private int quantity_ = 0;
  /**
   * <pre>
   * Corresponds to "quantity"
   * </pre>
   *
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int COPIESAVAILABLE_FIELD_NUMBER = 3;
  private int copiesAvailable_ = 0;
  /**
   * <pre>
   * Corresponds to "copiesAvailable"
   * </pre>
   *
   * <code>int32 copiesAvailable = 3;</code>
   * @return The copiesAvailable.
   */
  @java.lang.Override
  public int getCopiesAvailable() {
    return copiesAvailable_;
  }

  public static final int GENRE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object genre_ = "";
  /**
   * <pre>
   * Corresponds to "genre"
   * </pre>
   *
   * <code>string genre = 4;</code>
   * @return The genre.
   */
  @java.lang.Override
  public java.lang.String getGenre() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genre_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Corresponds to "genre"
   * </pre>
   *
   * <code>string genre = 4;</code>
   * @return The bytes for genre.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenreBytes() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genre_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISBN_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isbn_ = "";
  /**
   * <pre>
   * Corresponds to "isbn"
   * </pre>
   *
   * <code>string isbn = 5;</code>
   * @return The isbn.
   */
  @java.lang.Override
  public java.lang.String getIsbn() {
    java.lang.Object ref = isbn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isbn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Corresponds to "isbn"
   * </pre>
   *
   * <code>string isbn = 5;</code>
   * @return The bytes for isbn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsbnBytes() {
    java.lang.Object ref = isbn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isbn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 6;
  private double price_ = 0D;
  /**
   * <pre>
   * Corresponds to "price"
   * </pre>
   *
   * <code>double price = 6;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int PUBLICATIONYEAR_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object publicationYear_ = "";
  /**
   * <pre>
   * Corresponds to "publicationYear"
   * </pre>
   *
   * <code>string publicationYear = 7;</code>
   * @return The publicationYear.
   */
  @java.lang.Override
  public java.lang.String getPublicationYear() {
    java.lang.Object ref = publicationYear_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      publicationYear_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Corresponds to "publicationYear"
   * </pre>
   *
   * <code>string publicationYear = 7;</code>
   * @return The bytes for publicationYear.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPublicationYearBytes() {
    java.lang.Object ref = publicationYear_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      publicationYear_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <pre>
   * Corresponds to "title"
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Corresponds to "title"
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bookId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, bookId_);
    }
    if (quantity_ != 0) {
      output.writeInt32(2, quantity_);
    }
    if (copiesAvailable_ != 0) {
      output.writeInt32(3, copiesAvailable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(genre_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, genre_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(isbn_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, isbn_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(6, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(publicationYear_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, publicationYear_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, title_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bookId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, bookId_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, quantity_);
    }
    if (copiesAvailable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, copiesAvailable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(genre_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, genre_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(isbn_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, isbn_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, price_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(publicationYear_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, publicationYear_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, title_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.catalog_svc.app.grpc.cart.CartItemProto)) {
      return super.equals(obj);
    }
    com.example.catalog_svc.app.grpc.cart.CartItemProto other = (com.example.catalog_svc.app.grpc.cart.CartItemProto) obj;

    if (!getBookId()
        .equals(other.getBookId())) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (getCopiesAvailable()
        != other.getCopiesAvailable()) return false;
    if (!getGenre()
        .equals(other.getGenre())) return false;
    if (!getIsbn()
        .equals(other.getIsbn())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getPublicationYear()
        .equals(other.getPublicationYear())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKID_FIELD_NUMBER;
    hash = (53 * hash) + getBookId().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (37 * hash) + COPIESAVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getCopiesAvailable();
    hash = (37 * hash) + GENRE_FIELD_NUMBER;
    hash = (53 * hash) + getGenre().hashCode();
    hash = (37 * hash) + ISBN_FIELD_NUMBER;
    hash = (53 * hash) + getIsbn().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + PUBLICATIONYEAR_FIELD_NUMBER;
    hash = (53 * hash) + getPublicationYear().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.catalog_svc.app.grpc.cart.CartItemProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.catalog_svc.app.grpc.cart.CartItemProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cart.CartItemProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cart.CartItemProto)
      com.example.catalog_svc.app.grpc.cart.CartItemProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.catalog_svc.app.grpc.cart.CartProto.internal_static_cart_CartItemProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.catalog_svc.app.grpc.cart.CartProto.internal_static_cart_CartItemProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.catalog_svc.app.grpc.cart.CartItemProto.class, com.example.catalog_svc.app.grpc.cart.CartItemProto.Builder.class);
    }

    // Construct using com.example.catalog_svc.app.grpc.cart.CartItemProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bookId_ = "";
      quantity_ = 0;
      copiesAvailable_ = 0;
      genre_ = "";
      isbn_ = "";
      price_ = 0D;
      publicationYear_ = "";
      title_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.catalog_svc.app.grpc.cart.CartProto.internal_static_cart_CartItemProto_descriptor;
    }

    @java.lang.Override
    public com.example.catalog_svc.app.grpc.cart.CartItemProto getDefaultInstanceForType() {
      return com.example.catalog_svc.app.grpc.cart.CartItemProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.catalog_svc.app.grpc.cart.CartItemProto build() {
      com.example.catalog_svc.app.grpc.cart.CartItemProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.catalog_svc.app.grpc.cart.CartItemProto buildPartial() {
      com.example.catalog_svc.app.grpc.cart.CartItemProto result = new com.example.catalog_svc.app.grpc.cart.CartItemProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.catalog_svc.app.grpc.cart.CartItemProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bookId_ = bookId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.copiesAvailable_ = copiesAvailable_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.genre_ = genre_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isbn_ = isbn_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.publicationYear_ = publicationYear_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.title_ = title_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.catalog_svc.app.grpc.cart.CartItemProto) {
        return mergeFrom((com.example.catalog_svc.app.grpc.cart.CartItemProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.catalog_svc.app.grpc.cart.CartItemProto other) {
      if (other == com.example.catalog_svc.app.grpc.cart.CartItemProto.getDefaultInstance()) return this;
      if (!other.getBookId().isEmpty()) {
        bookId_ = other.bookId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (other.getCopiesAvailable() != 0) {
        setCopiesAvailable(other.getCopiesAvailable());
      }
      if (!other.getGenre().isEmpty()) {
        genre_ = other.genre_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getIsbn().isEmpty()) {
        isbn_ = other.isbn_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (!other.getPublicationYear().isEmpty()) {
        publicationYear_ = other.publicationYear_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bookId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              quantity_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              copiesAvailable_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              genre_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              isbn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 49: {
              price_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 58: {
              publicationYear_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object bookId_ = "";
    /**
     * <pre>
     * Corresponds to "bookId"
     * </pre>
     *
     * <code>string bookId = 1;</code>
     * @return The bookId.
     */
    public java.lang.String getBookId() {
      java.lang.Object ref = bookId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "bookId"
     * </pre>
     *
     * <code>string bookId = 1;</code>
     * @return The bytes for bookId.
     */
    public com.google.protobuf.ByteString
        getBookIdBytes() {
      java.lang.Object ref = bookId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "bookId"
     * </pre>
     *
     * <code>string bookId = 1;</code>
     * @param value The bookId to set.
     * @return This builder for chaining.
     */
    public Builder setBookId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bookId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "bookId"
     * </pre>
     *
     * <code>string bookId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookId() {
      bookId_ = getDefaultInstance().getBookId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "bookId"
     * </pre>
     *
     * <code>string bookId = 1;</code>
     * @param value The bytes for bookId to set.
     * @return This builder for chaining.
     */
    public Builder setBookIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bookId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <pre>
     * Corresponds to "quantity"
     * </pre>
     *
     * <code>int32 quantity = 2;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <pre>
     * Corresponds to "quantity"
     * </pre>
     *
     * <code>int32 quantity = 2;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {

      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "quantity"
     * </pre>
     *
     * <code>int32 quantity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000002);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private int copiesAvailable_ ;
    /**
     * <pre>
     * Corresponds to "copiesAvailable"
     * </pre>
     *
     * <code>int32 copiesAvailable = 3;</code>
     * @return The copiesAvailable.
     */
    @java.lang.Override
    public int getCopiesAvailable() {
      return copiesAvailable_;
    }
    /**
     * <pre>
     * Corresponds to "copiesAvailable"
     * </pre>
     *
     * <code>int32 copiesAvailable = 3;</code>
     * @param value The copiesAvailable to set.
     * @return This builder for chaining.
     */
    public Builder setCopiesAvailable(int value) {

      copiesAvailable_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "copiesAvailable"
     * </pre>
     *
     * <code>int32 copiesAvailable = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCopiesAvailable() {
      bitField0_ = (bitField0_ & ~0x00000004);
      copiesAvailable_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object genre_ = "";
    /**
     * <pre>
     * Corresponds to "genre"
     * </pre>
     *
     * <code>string genre = 4;</code>
     * @return The genre.
     */
    public java.lang.String getGenre() {
      java.lang.Object ref = genre_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genre_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "genre"
     * </pre>
     *
     * <code>string genre = 4;</code>
     * @return The bytes for genre.
     */
    public com.google.protobuf.ByteString
        getGenreBytes() {
      java.lang.Object ref = genre_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "genre"
     * </pre>
     *
     * <code>string genre = 4;</code>
     * @param value The genre to set.
     * @return This builder for chaining.
     */
    public Builder setGenre(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      genre_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "genre"
     * </pre>
     *
     * <code>string genre = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenre() {
      genre_ = getDefaultInstance().getGenre();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "genre"
     * </pre>
     *
     * <code>string genre = 4;</code>
     * @param value The bytes for genre to set.
     * @return This builder for chaining.
     */
    public Builder setGenreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      genre_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object isbn_ = "";
    /**
     * <pre>
     * Corresponds to "isbn"
     * </pre>
     *
     * <code>string isbn = 5;</code>
     * @return The isbn.
     */
    public java.lang.String getIsbn() {
      java.lang.Object ref = isbn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isbn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "isbn"
     * </pre>
     *
     * <code>string isbn = 5;</code>
     * @return The bytes for isbn.
     */
    public com.google.protobuf.ByteString
        getIsbnBytes() {
      java.lang.Object ref = isbn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isbn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "isbn"
     * </pre>
     *
     * <code>string isbn = 5;</code>
     * @param value The isbn to set.
     * @return This builder for chaining.
     */
    public Builder setIsbn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isbn_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "isbn"
     * </pre>
     *
     * <code>string isbn = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsbn() {
      isbn_ = getDefaultInstance().getIsbn();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "isbn"
     * </pre>
     *
     * <code>string isbn = 5;</code>
     * @param value The bytes for isbn to set.
     * @return This builder for chaining.
     */
    public Builder setIsbnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isbn_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <pre>
     * Corresponds to "price"
     * </pre>
     *
     * <code>double price = 6;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <pre>
     * Corresponds to "price"
     * </pre>
     *
     * <code>double price = 6;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {

      price_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "price"
     * </pre>
     *
     * <code>double price = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000020);
      price_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object publicationYear_ = "";
    /**
     * <pre>
     * Corresponds to "publicationYear"
     * </pre>
     *
     * <code>string publicationYear = 7;</code>
     * @return The publicationYear.
     */
    public java.lang.String getPublicationYear() {
      java.lang.Object ref = publicationYear_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publicationYear_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "publicationYear"
     * </pre>
     *
     * <code>string publicationYear = 7;</code>
     * @return The bytes for publicationYear.
     */
    public com.google.protobuf.ByteString
        getPublicationYearBytes() {
      java.lang.Object ref = publicationYear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicationYear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "publicationYear"
     * </pre>
     *
     * <code>string publicationYear = 7;</code>
     * @param value The publicationYear to set.
     * @return This builder for chaining.
     */
    public Builder setPublicationYear(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      publicationYear_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "publicationYear"
     * </pre>
     *
     * <code>string publicationYear = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicationYear() {
      publicationYear_ = getDefaultInstance().getPublicationYear();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "publicationYear"
     * </pre>
     *
     * <code>string publicationYear = 7;</code>
     * @param value The bytes for publicationYear to set.
     * @return This builder for chaining.
     */
    public Builder setPublicationYearBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      publicationYear_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * Corresponds to "title"
     * </pre>
     *
     * <code>string title = 8;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "title"
     * </pre>
     *
     * <code>string title = 8;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Corresponds to "title"
     * </pre>
     *
     * <code>string title = 8;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "title"
     * </pre>
     *
     * <code>string title = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Corresponds to "title"
     * </pre>
     *
     * <code>string title = 8;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:cart.CartItemProto)
  }

  // @@protoc_insertion_point(class_scope:cart.CartItemProto)
  private static final com.example.catalog_svc.app.grpc.cart.CartItemProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.catalog_svc.app.grpc.cart.CartItemProto();
  }

  public static com.example.catalog_svc.app.grpc.cart.CartItemProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CartItemProto>
      PARSER = new com.google.protobuf.AbstractParser<CartItemProto>() {
    @java.lang.Override
    public CartItemProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CartItemProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CartItemProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.catalog_svc.app.grpc.cart.CartItemProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

