// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cart/cart.proto
// Protobuf Java Version: 4.29.1

package com.example.catalog_svc.app.grpc.cart;

public final class CartProto {
  private CartProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      CartProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_CartItemRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cart_CartItemRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_CartItemProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cart_CartItemProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_CartItemResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cart_CartItemResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017cart/cart.proto\022\004cart\"*\n\024CartItemReque" +
      "stProto\022\022\n\ncustomerId\030\001 \001(\t\"\236\001\n\rCartItem" +
      "Proto\022\016\n\006bookId\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\022" +
      "\027\n\017copiesAvailable\030\003 \001(\005\022\r\n\005genre\030\004 \001(\t\022" +
      "\014\n\004isbn\030\005 \001(\t\022\r\n\005price\030\006 \001(\001\022\027\n\017publicat" +
      "ionYear\030\007 \001(\t\022\r\n\005title\030\010 \001(\t\";\n\025CartItem" +
      "ResponseProto\022\"\n\005items\030\001 \003(\0132\023.cart.Cart" +
      "ItemProto2h\n\017GrpcCartService\022U\n\032GetCartI" +
      "temByCustomerProto\022\032.cart.CartItemReques" +
      "tProto\032\033.cart.CartItemResponseProtoB<\n%c" +
      "om.example.catalog_svc.app.grpc.cartB\tCa" +
      "rtProtoP\001Z\006./cartb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cart_CartItemRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_CartItemRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cart_CartItemRequestProto_descriptor,
        new java.lang.String[] { "CustomerId", });
    internal_static_cart_CartItemProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cart_CartItemProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cart_CartItemProto_descriptor,
        new java.lang.String[] { "BookId", "Quantity", "CopiesAvailable", "Genre", "Isbn", "Price", "PublicationYear", "Title", });
    internal_static_cart_CartItemResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cart_CartItemResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cart_CartItemResponseProto_descriptor,
        new java.lang.String[] { "Items", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
