// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cart-delete.proto
// Protobuf Java Version: 4.29.1

package com.example.catalog_svc.app.grpc.cart;

public interface DeleteCartRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.DeleteCartRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customerId = 1;</code>
   * @return The customerId.
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customerId = 1;</code>
   * @return The bytes for customerId.
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();
}
