databases:
  order_svc_db:
    username: root
    password: G5!kT@2y9B#zU8%w
    host: localhost
    database_name: bookshop-order
    port: 3306

security:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    issuer: example.com